name: ROS

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: UR Robot Driver build
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE $GITHUB_REPOSITORY \
          bash -c "
          git clone https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git src/Universal_Robots_ROS2_Driver \
          && vcs import --skip-existing < src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver.repos src \
          && apt-get update \
          && rosdep update \
          && rosdep install --from-paths src --ignore-src -y -r --rosdistro=galactic \
          && colcon build --packages-up-to ur_robot_driver --cmake-args '-DCMAKE_BUILD_TYPE=Release'
          "
