name: ROS

on:
  pull_request:
  workflow_dispatch:
    
jobs:
  ur5-driver:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout code
        uses: actions/checkout@v2
      -
        name: UR5 Driver build
        run: |
          docker build -t $GITHUB_REPOSITORY -f ./.devcontainer/Dockerfile .
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE $GITHUB_REPOSITORY \
          bash -c "
          git clone https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver.git src/Universal_Robots_ROS2_Driver \
          && vcs import --skip-existing < src/Universal_Robots_ROS2_Driver/Universal_Robots_ROS2_Driver.repos src \
          && apt-get update \
          && rosdep update \
          && rosdep install --from-paths src --ignore-src -y -r --rosdistro=galactic \
          && colcon build --merge-install --packages-up-to ur_robot_driver --cmake-args '-DCMAKE_BUILD_TYPE=Release'
          "
      -
        name: UR5 Driver install
        run: |
          docker pull ros:galactic
          docker run -v $GITHUB_WORKSPACE:$GITHUB_WORKSPACE -w $GITHUB_WORKSPACE ros:galactic \
          bash -c "
          apt-get update \
          && rosdep update \
          && rosdep install --from-paths src --ignore-src -y -r --rosdistro=galactic \
          && cp -r install/* /opt/ros/galactic/.
          "
          docker commit `docker ps -l | grep galactic | awk '{print $1;}'` ros:galactic.ur5driver
          docker save ros:galactic.ur5driver | gzip | pv > ./ros.galactic.ur5driver.tar.gz
      - 
        uses: actions/upload-artifact@v2
        with:
          name: 'UR5 driver docker image'
          path: ./ros.galactic.ur5driver.tar.gz